export const HB_ID_PREFIX = "HB-";

export const STORAGE_KEYS = {
  SESSION: "HB_SESSION",
  USERS: "HB_USERS",
  PROFILES: "HB_PROFILES",
  SHORTLISTS: "HB_SHORTLISTS",
  INTERESTS: "HB_INTERESTS",
  BLOCKS: "HB_BLOCKS",
  REPORTS: "HB_REPORTS",
  CHAT_THREADS: "HB_CHAT_THREADS",
};
